### ISSUE TITLE
Requesting help getting this set up

### ISSUE THREAD

**Issue by austincap** [alanszlosek/voxeling#2]
This looks awesome and the game works perfectly [here](http://voxeling.greaterscope.com/), but when I use the instructions [here](https://github.com/alanszlosek/voxeling) to create my own server, only the css and pictures load. No voxels.

I reckon I need to do something like 'portforwarding node', but I'm not sure what. Which ports do I forward? I see 10005 in the code but non 9966. How could I change it to use a custom port (2077)? I have access to my router settings. Can someone point me in the right direction? What should I do at the `vim config.js` step? Thanks!

Relevant info: Windows 7 x64 using Windows commandline, latest appropriate version of node and npm

**Comment by austincap** [comment]
![canvas](https://cloud.githubusercontent.com/assets/3488809/15870520/8db22824-2cbe-11e6-92f0-dcd93d00bd61.png)
This is what it looks like if I follow the instructions exactly from [here](https://github.com/alanszlosek/voxeling) except when I did nothing for the step: `vim config.js`

**Comment by alanszlosek** [comment]
@austincap Have you tried using Chrome? Firefox isn't supported yet.

If you're running the project on a single machine I wouldn't think port forwarding is necessary. However, I've never tried running the server on windows.

Port 9966 is beefy's default port. `client.sh` uses beefy to set up a test HTTP server for serving HTML, CSS, JS and images. But you can use any webserver for this. I use nginx on voxeling.greaterscope.com

Port 10005 is the default port for the websocket connection. You can change the port in config.js, but make sure the `server`, `websocketBindAddress` and `websocketBindPort` values correspond to each other. `server` is used by `client-worker.js` within Chrome to connect to the server. The other two are used by `server.js` to set up the listening port and interface.

You might also need to remove the mysql object from config.js. `server.js` line 24 will try to use mysql as a chunk store if that key is present.

Hope that clears things up. If you have any other questions, let me know!

**Comment by austincap** [comment]
I reinstalled the most recent version of Chrome on my computer and used a fresh clone of your voxeling project but I'm still getting the same error:
![untitled](https://cloud.githubusercontent.com/assets/3488809/15947581/42f55e02-2e6a-11e6-88e0-48b76410cac2.png)

I get the same thing when I deleted the mysql object too. It looked like this btw: 

```
module.exports = {
    chunkSize: 32,
    drawDistance: 2,
    removeDistance: 3,

    initialPosition: [16.5, 25.5, 16.5],
    worldRadius: 10,
    chunkFolder: 'chunks/test/',
    mysql: {
        connectionLimit: 10,
        user: 'voxeling',
        password: 'voxeling',
        database: 'voxeling',
        host: 'localhost'
    },
    server: 'http://127.0.0.1:10005',
    websocketBindAddress: '127.0.0.1',
    websocketBindPort: 10005,
    maxPlayers: 10,

    textures: [
        {
            value: 1,
            name: 'grass+dirt',
            sides: [
                14,
                302, 302, 302, 302,
                3
            ]
        },
```

What are you supposed to do at the `vim config.js` step? I shouldn't have to change anything there, right?

**Comment by alanszlosek** [comment]
Do any errors show in the Chrome devtools Console?

Copying config-example.js to config.js and removing the mysql object should be all you need to do. I cloned the repo on my Mac and the generic world comes up for me. Maybe it's a Windows issue. Are you seeing any errors in the server or client.sh windows?

**Comment by austincap** [comment]
I'm not getting any errors anywhere... For what it's worth, [WebCraft](https://github.com/Overv/WebCraft) is working fine for me.

![image2](https://cloud.githubusercontent.com/assets/3488809/16167156/dab649b2-34bf-11e6-9758-f57dbe6b3d17.png)

**Comment by alanszlosek** [comment]
From your terminal output at the top-left it I see that the www/client-worker.js file is 0 bytes in size. Can you convert the commands in worker.sh (the file that builds www/client-worker.js) into something that makes sense for windows, and see if that helps?

**Comment by austincap** [comment]
I changed all the `/` to `\\` in worker.sh, client-worker.js, client.js, client.sh, & config.js. Nothing changed from before.

**Comment by alanszlosek** [comment]
Is www\client-worker.js an empty file? Try running browserify on client-worker.js with the "-o www\client-worker.js" parameter.

**Comment by austincap** [comment]
www\client-worker.js is an empty file. I tried entering the command three different ways, and I got 2 different errors:

![untirrtled](https://cloud.githubusercontent.com/assets/3488809/16287750/97c07504-38b3-11e6-890b-88e86950dd03.png)

**Comment by alanszlosek** [comment]
Second attempt says it can't find the "config" module ... Did you copy config-example.js to config.js?

**Comment by austincap** [comment]
Yes I did and I deleted the mysql object:

```
module.exports = {
 chunkSize: 32,
 drawDistance: 2,
 removeDistance: 3,

initialPosition: [16.5, 25.5, 16.5],
worldRadius: 10,
chunkFolder: 'chunks\\test\\',
server: 'http://127.0.0.1:10005',
websocketBindAddress: '127.0.0.1',
websocketBindPort: 10005,
maxPlayers: 10,

textures: [
    {
        value: 1,
        name: 'grass+dirt',
        sides: [
            14,
            302, 302, 302, 302,
            3
        ]
    },
    {
        value: 14,
        name: 'grass',
        src: '\\testbdcraft\\default_grass.png'
    },
    {
        value: 17,
        name: 'grass2',
        src: '\\testbdcraft\\default_grass_footsteps.png'
    },
    {
        value: 3,
        name: 'dirt',
        src: '\\testbdcraft\\default_dirt.png'
    },
    {
        value: 302,
        name: 'grass_dirt',
        src: '\\testbdcraft\\default_grass_side.png',
        hidden: true
    },

    {
        value: 2,
        name: 'brick',
        src: '\\testbdcraft\\default_brick.png'
    },
    {
        value: 9,
        name: 'brick2',
        src: '\\testbdcraft\\default_brick.png',
        hidden: true
    },
    {
        value: 10,
        name: 'brick3',
        src: '\\testbdcraft\\default_brick.png',
        hidden: true
    },

    {
        value: 4,
        name: 'coal',
        src: '\\testbdcraft\\default_mineral_coal.png'
    },
    {
        value: 13,
        name: 'iron',
        src: '\\testbdcraft\\default_mineral_iron.png'
    },
    {
        value: 19,
        name: 'clay',
        src: '\\testbdcraft\\default_clay.png'
    },
    {
        value: 18,
        name: 'sandstone',
        src: '\\testbdcraft\\default_sandstone.png'
    },
    {
        value: 11,
        name: 'cobble',
        src: '\\testbdcraft\\default_cobble.png'
    },
    {
        value: 12,
        name: 'cobble2',
        src: '\\testbdcraft\\default_cobble.png',
        hidden: true
    },
    {
        value: 15,
        name: 'moss cobble',
        src: '\\testbdcraft\\default_mossycobble.png'
    },

    {
        value: 7,
        name: 'lava',
        src: '\\testbdcraft\\default_lava.png'
    },

    {
        value: 6,
        name: 'water',
        src: '\\testbdcraft\\default_water.png'
    },
    {
        value: 16,
        name: 'ice',
        src: '\\textures\\ice.png',
        hidden: true
    },
    {
        value: 20,
        name: 'snow',
        src: '\\textures\\sparkly_snow.png',
        hidden: true
    },

    {
        value: 8,
        name: 'chest',
        sides: [
            300,
            301, 301, 301, 301,
            301
        ]
    },
    {
        value: 300,
        name: 'chest top',
        src: '\\testbdcraft\\default_chest_top.png',
        hidden: true
    },
    {
        value: 301,
        name: 'chest side',
        src: '\\testbdcraft\\default_chest_side.png',
        hidden: true
    },

    {
        value: 22,
        name: 'wood',
        src: '\\testbdcraft\\default_wood.png'
    },
    {
        value: 24,
        name: 'tree',
        sides: [
            303,
            304, 304, 304, 304,
            303
        ]
    },
    {
        value: 303,
        name: 'tree_top',
        src: '\\testbdcraft\\default_tree_top.png',
        hidden: true
    },
    {
        value: 304,
        name: 'tree_side',
        src: '\\testbdcraft\\default_tree.png',
        hidden: true
    },
    {
        value: 100,
        name: 'leaves',
        src: '\\testbdcraft\\default_leaves.png'
    },

    {
        value: 27,
        name: 'black wool',
        src: '\\testbdcraft\\wool_black.png'
    },
    {
        value: 34,
        name: 'grey wool',
        src: '\\testbdcraft\\wool_grey.png'
    },
    {
        value: 32,
        name: 'dk grey wool',
        src: '\\testbdcraft\\wool_dark_grey.png'
    },
    {
        value: 29,
        name: 'brown wool',
        src: '\\testbdcraft\\wool_brown.png'
    },
    {
        value: 28,
        name: 'blue wool',
        src: '\\testbdcraft\\wool_blue.png'
    },
    {
        value: 30,
        name: 'cyan wool',
        src: '\\testbdcraft\\wool_cyan.png'
    },
    {
        value: 33,
        name: 'green wool',
        src: '\\testbdcraft\\wool_green.png'
    },
    {
        value: 31,
        name: 'dk green wool',
        src: '\\testbdcraft\\wool_dark_green.png'
    },
    {
        value: 35,
        name: 'magenta wool',
        src: '\\testbdcraft\\wool_magenta.png'
    },
    {
        value: 39,
        name: 'violet wool',
        src: '\\testbdcraft\\wool_violet.png'
    },
    {
        value: 37,
        name: 'pink wool',
        src: '\\testbdcraft\\wool_pink.png'
    },
    {
        value: 38,
        name: 'red wool',
        src: '\\testbdcraft\\wool_red.png'
    },
    {
        value: 21,
        name: 'yellow wool',
        src: '\\testbdcraft\\wool_yellow.png'
    },
    {
        value: 36,
        name: 'orange wool',
        src: '\\testbdcraft\\wool_orange.png'
    },
    {
        value: 5,
        name: 'white wool',
        src: '\\testbdcraft\\wool_white.png'
    },

    {
        value: 101,
        name: 'glass',
        src: '\\textures\\glass.png'
    },

    {
        value: 50,
        name: 'player',
        src: '\\textures\\player.png',
        hidden: true
    },
    {
        value: 51,
        name: 'substack',
        src: '\\textures\\substack.png',
        hidden: true
    },
    {
        value: 52,
        name: 'viking',
        src: '\\textures\\viking.png',
        hidden: true
    }

]
}
```

**Comment by alanszlosek** [comment]
Think we're getting close .... Change the protocol in the server key of config.js to "ws://" instead of "http://". The client-worker.js connects using websockets, not http. So the full line should be:

`server: 'ws://127.0.0.1:10005',`

I'm surprised you weren't seeing any errors in the Chrome Console about this ... If I use http instead of ws, my error console says "client-worker.js:6384 Uncaught SyntaxError: Failed to construct 'WebSocket': The URL's scheme must be either 'ws' or 'wss'. 'http' is not allowed". Have you tried opening the Error Console before you attempt to load http://127.0.0.1:9966 ?

Also, the "src" values for each texture are used to construct image URLs, so they should be forward slashes instead of backslashes. However, I ran a test in Chrome and the browser doesn't seem to care much.

**Comment by alanszlosek** [comment]
@austincap Any luck?

**Comment by alanszlosek** [comment]
@austincap Checking in again ... did you get it working?

**Comment by austincap** [comment]
Still nothing. Thank you so much for all your help, but I think I'm just gonna give up... Sorry!

**Comment by alanszlosek** [comment]
Understandable. Take care!
